routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
// Route::get("nicePosts/{nicePost}/duplicate", ['as' => 'nicePosts.duplicate', 'uses' => 'NicePostController@duplicate']);
// Route::resource("nicePosts","NicePostController");
// Route::get("beautifulTags/{beautifulTag}/duplicate", ['as' => 'beautifulTags.duplicate', 'uses' => 'BeautifulTagController@duplicate']);
// Route::resource("beautifulTags","BeautifulTagController");
// Route::get("brilliantCategories/{brilliantCategory}/duplicate", ['as' => 'brilliantCategories.duplicate', 'uses' => 'BrilliantCategoryController@duplicate']);
// Route::resource("brilliantCategories","BrilliantCategoryController");
// Route::get("goodComments/{goodComment}/duplicate", ['as' => 'goodComments.duplicate', 'uses' => 'GoodCommentController@duplicate']);
// Route::resource("goodComments","GoodCommentController");

Auth::routes();

Route::get('/', function () { return view('auth.login'); })->middleware('guest');


Route::get('/home', 'HomeController@index')->name('home');

Route::get("users/{user}/duplicate", ['as' => 'users.duplicate', 'uses' => 'UserController@duplicate']);

Route::resource("users","UserController");

Route::get("planners/{planner}/duplicate",
    ['as' => 'planners.duplicate', 'uses' => 'PlannerController@duplicate']);
Route::resource("planners","PlannersController");

Route::get("users/{user}/duplicate",
    ['as' => 'users.duplicate', 'uses' => 'UserController@duplicate']);
Route::resource("users","UserController");
Route::get("planners/{planner}/duplicate",
    ['as' => 'planners.duplicate', 'uses' => 'PlannerController@duplicate']);
Route::resource("planners","PlannerController");
Route::get("notes/{note}/duplicate",
    ['as' => 'notes.duplicate', 'uses' => 'NoteController@duplicate']);
Route::resource("notes","NoteController");
Route::get("tags/{tag}/duplicate",
    ['as' => 'tags.duplicate', 'uses' => 'TagController@duplicate']);
Route::resource("tags","TagController");
Route::get("reminders/{reminder}/duplicate",
    ['as' => 'reminders.duplicate', 'uses' => 'ReminderController@duplicate']);
Route::resource("reminders","ReminderController");

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::resource('planners.notes', 'PlannerNoteController');
// Route::resource('notes.reminders', 'RemainderController');
// Route::get('/planners/{planner}/notes/create', 'NoteController@create');

app/Note.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Note extends Model
{


	// Mass Assignment
	protected $fillable = ['planner_id','note',];


	// Validate Rule
    public static function getValidateRule(Note $note=null){
        if($note){
            $ignore_unique = $note->id;
        }else{
            $ignore_unique = 'NULL';
        }
        $table_name = 'notes';
        $validation_rule = [

            'model.planner_id' => 'integer|nullable',
            'model.note' => 'string',


        ];
        if($note){

        }
        return $validation_rule;
    }

	public function reminders() {
		return $this->hasMany('App\Reminder');
	}


	public function planner() {
		return $this->belongsTo('App\Planner');
	}




	public static function getLists() {
		$lists = [];
		$lists['Planner'] = Planner::pluck( 'name' ,'id' );
		$lists['Reminder'] = Reminder::pluck( 'when' ,'id' );
		return $lists;
	}
}

app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;

use App\Note;
use App\Planner;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class NoteController extends Controller
{
    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
		$notes = new Note;

        // (1)filltering
        if( is_array($request->input('q')) ){

            foreach( $request->input('q') as $key => $value ){

                if($key !== 's'){

                    $pettern = '#([^\.]*)\.?([^\.]*)_([^\._]*)#u';
                    preg_match($pettern,$key,$m);

                    $collumn_name = $m[1];
                    $related_column_name = $m[2];

                    if($m[3] == 'eq'){
                        $operator = '=';
                    }elseif($m[3] == 'cont'){
                        $operator = 'like';
                        $value = '%'.$value.'%';
                    }elseif($m[3] == 'gt'){
                        $operator = '>=';
                    }elseif($m[3] == 'lt'){
                        $operator = '<=';
                    }

                    if( $related_column_name !== '' ){  // search at related table column

                        $notes = $notes->whereHas($collumn_name, function($q) use($related_column_name, $operator, $value){
    						$q->where( $related_column_name, $operator, $value );
                        });

                    }else{
                        $notes = $notes->where( $collumn_name, $operator, $value );
                    }
                }
            }
        }
        $notes = $notes->get();



        // (2)sort
        $q_s = $request->input('q.s');
        if($q_s){

            // sort dir and sort column
            if( substr( $q_s,-5,5 ) === '_desc' ){
                $sort_column = substr( $q_s, 0, strlen($q_s)-5 );
                $notes = $notes->sortByDesc($sort_column);
            }elseif( substr( $q_s,-4,4 ) === '_asc' ){
                $sort_column = substr( $q_s, 0, strlen($q_s)-4 );
                $notes = $notes->sortBy($sort_column);
            }

        }else{
            $notes = $notes->sortByDesc('id');
        }



        // (3)paginate
        $notes = $notes->paginate(10);

		return view('notes.index', compact('notes'));
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('notes.create')->with( 'lists', Note::getLists() );
    }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return "haha";
  //       $this->validate_custom($request);

  //       $input = $request->input('model');

  //       DB::beginTransaction();


		// //create data
		// $note = Note::create( $input );

  //       //sync(attach/detach)
  //       if($request->input('pivots')){
  //           $this->sync($request->input('pivots'), $note);
  //       }

  //       DB::commit();

		// return redirect()->route('notes.index')->with('message', 'Item created successfully.');
    }



    /**
     * Display the specified resource.
     *
     * @param  \App\Note  $note     * @return \Illuminate\Http\Response
     */
    public function show(Note $note)
    {
		return view('notes.show', compact('note'));
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Note  $note     * @return \Illuminate\Http\Response
     */
    public function edit(Note $note)
    {
		return view('notes.edit', compact('note'))->with( 'lists', Note::getLists() );
    }



	/**
	 * Show the form for duplicatting the specified resource.
	 *
	 * @param \App\Note  $note	 * @return \Illuminate\Http\Response
	 */
	public function duplicate(Note $note)
	{
		return view('notes.duplicate', compact('note'))->with( 'lists', Note::getLists() );
	}



    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Note  $note     * @return \Illuminate\Http\Response
     */
    public function update(Note $note, Request $request)
    {
        $this->validate_custom($request, $note);

        $input = $request->input('model');

        DB::beginTransaction();


		//update data
		$note->update( $input );

        //sync(attach/detach)
        if($request->input('pivots')){
            $this->sync($request->input('pivots'), $note);
        }

        DB::commit();

		return redirect()->route('notes.index')->with('message', 'Item updated successfully.');
    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Note  $note     * @return \Illuminate\Http\Response
     */
    public function destroy(Note $note)
    {
		$note->delete();
		return redirect()->route('notes.index')->with('message', 'Item deleted successfully.');
    }

    /**
     * validate input data.
     *
     * @return array
     */
    public function validate_custom(Request $request, Note $note = null)
    {
        $request->validate(Note::getValidateRule($note));
    }

    /**
     * sync pivot data
     *
     * @return void
     */
    public function sync($pivots_data, Note $note)
    {
        foreach( $pivots_data as $pivot_child_model_name => $pivots ){

            // remove 'id'
            foreach($pivots as &$value){
                if( array_key_exists('id', $value) ){
                    unset($value['id']);
                }
            }unset($value);

            $method = camel_case( str_plural($pivot_child_model_name) );
            $note->$method()->sync($pivots);
        }
    }
}

resources/views/notes/_form.blade.php
<div class="form-group">
  <label for="note-field">Nota</label>

  <textarea class="form-control
  @if($errors->any()) @if($errors->has("model.note")) is-invalid @else is-valid @endif @endif;
  " id="note-field" name="model[note]" rows="3" required>@if($errors->any()){{ old('model.note') }}@else{{ $note->note or '' }}@endif</textarea>

  @if($errors->has("model.note"))
    <div class="invalid-feedback">{{ $errors->first("model.note") }}</div>
  @else
    <div class="invalid-feedback">Invalid!</div>
  @endif
</div>




<p>Uhu: {{ var_dump($lists) }}</p>

{{-- <div class="form-group">
  <label for="planner_id-field">Planner</label>
  <select class="form-control
  @if($errors->any()) @if($errors->has("model.planner_id")) is-invalid @else is-valid @endif @endif
  " id="planner_id-field" name="model[planner_id]">
    <option value=""></option>
  @foreach( $lists["Planner"] as $list_key => $list_item )
    <option value="{{ $list_key }}"
      @if($errors->any())
        @if( old('planner_id') == $list_key ) selected='selected' @endif
      @else
        @if( isset($note) && $note->planner_id==$list_key )  selected='selected' @endif
      @endif
   >{{ $list_item }}</option>
  @endforeach
  </select>
  @if($errors->has("model.planner_id"))
    <div class="invalid-feedback">{{ $errors->first("model.planner_id") }}</div>
  @else
    <div class="invalid-feedback">Invalid!</div>
  @endif
</div> --}}

resources/views/notes/_table.blade.php
<div class="row">
    <div class="col-md-12">

        @if($notes->count())

            <table class="table table-sm table-striped sp-omit">
              <thead>
                <tr>
                  <th scope="col"><div class="d-flex">
                    @if( method_exists($notes, 'appends') )
                      <a href="javascript:sortByColumn('id')">ID</a>
                      @if( Request::input('q.s') == 'id_asc' )<i class="material-icons">arrow_drop_up</i>
                      @elseif( Request::input('q.s') == 'id_desc' )<i class="material-icons">arrow_drop_down</i> @endif
                    @else
                      ID
                    @endif
                  </div></th>
                  <th scope="col"><div class="d-flex">
                    @if( method_exists($notes, 'appends') )
                      <a href="javascript:sortByColumn('note')">Nota</a>
                      @if( Request::input('q.s') == 'note_asc' )<i class="material-icons">arrow_drop_up</i>
                      @elseif( Request::input('q.s') == 'note_desc' )<i class="material-icons">arrow_drop_down</i> @endif
                    @else
                      Nota                    @endif
                  </div></th>

                  <th scope="col">Planner</th>

                  <th scope="col">Reminder</th>


                  <th class="text-right" scope="col">OPTIONS</th>
                </tr>
              </thead>
              <tbody>
                @foreach($notes as $note)
                    <tr>
                      <td scope="row"><a href="{{ route('notes.show', $note->id) }}">{{$note->id}}</a></td>
                      <td>{{$note->note}}</td>

                      <td>@if($note->planner)<a href="{{ route('planners.show', $note->planner->id) }}">{{ $note->planner->name }}</a>@else - @endif</td>

                      <td>
                          @foreach($note->reminders as $reminder)
                                        @if (!$loop->first) , @endif
                                        <a href="{{ route('reminders.show', $reminder->id) }}">{{ $reminder->when }}</a>
                          @endforeach
                      </td>


                      <td class="text-right">
                        <div class="btn-group" role="group">
                            <a class="btn btn-sm btn-primary" href="{{ route('notes.duplicate', $note->id) }}" data-toggle="tooltip" data-placement="top" title="Duplicate"><i class="material-icons d-block">add_to_photos</i></a>
                            <a class="btn btn-sm btn-warning" href="{{ route('notes.edit', $note->id) }}" data-toggle="tooltip" data-placement="top" title="Edit"><i class="material-icons d-block">edit</i></a>
                            <form method="POST" action="{{ route('notes.destroy', $note->id) }}" accept-charset="UTF-8" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Delete"><i class="material-icons d-block">delete</i></button>
                            </form>
                        </div>
                      </td>
                    </tr>
                @endforeach
              </tbody>
            </table>
            @if( method_exists($notes, 'appends') )
              {!! $notes->appends(Request::except('page'))->render() !!}
            @endif
        @else
            <h3 class="text-center alert alert-info">Empty!</h3>
        @endif
    </div>
</div>

resources/views/notes/create.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('notes.index') }}">{{ $model_title_list['notes'] }}</a></li>
        <li class="breadcrumb-item active">Create</li>
      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">add_circle</i>
        <span class="d-inline-block">{{ $model_title_list['notes'] }} / Create</span>
    </h1>

    <div class="row">
      <div class="col-md-12">
        <form method="POST" action="{{ route('notes.store') }}" accept-charset="UTF-8" class="needs-validation" novalidate>
          {{ csrf_field() }}

@include('notes._form', ['mode' => 'create'])

          <div class="d-flex justify-content-end">
            <a class="btn btn-secondary d-inline-flex mr-3" href="{{ route('notes.index') }}"><i class="material-icons mr-1">fast_rewind</i> Back</a>
            <button type="submit" class="btn btn-primary">Create</button>
          </div>

        </form>
      </div>
    </div>

@endsection

resources/views/notes/duplicate.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('notes.index') }}">{{ $model_title_list['notes'] }}</a></li>
        <li class="breadcrumb-item active">Duplicate</li>
      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">add_to_photos</i>
        <span class="d-inline-block">{{ $model_title_list['notes'] }} / Duplicate #{{$note->id}}</span>
    </h1> 

    <div class="row">
      <div class="col-md-12">
        <form method="POST" action="{{ route('notes.store') }}" accept-charset="UTF-8" class="needs-validation" novalidate>
          {{ csrf_field() }}

@include('notes._form', ['mode' => 'duplicate'])

          <div class="d-flex justify-content-end">
            <a class="btn btn-secondary d-inline-flex mr-3" href="{{ route('notes.index') }}"><i class="material-icons mr-1">fast_rewind</i> Back</a>
            <button type="submit" class="btn btn-primary">Duplicate</button>
          </div>

        </form>
      </div>
    </div>

@endsection

resources/views/notes/edit.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('notes.index') }}">{{ $model_title_list['notes'] }}</a></li>
        <li class="breadcrumb-item"><a href="{{ route('notes.show', $note->id) }}">{{ $note->id }}</a></li>
        <li class="breadcrumb-item active">Edit</li>
      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">edit</i>
        <span class="d-inline-block">{{ $model_title_list['notes'] }} / Edit #{{$note->id}}</span>
    </h1> 

    <div class="row">
      <div class="col-md-12">
        <form method="POST" action="{{ route('notes.update', $note->id) }}" accept-charset="UTF-8" class="needs-validation" novalidate>
          {{ method_field('PUT') }}
          {{ csrf_field() }}

@include('notes._form', ['mode' => 'edit'])

          <div class="d-flex justify-content-end">
            <a class="btn btn-secondary d-inline-flex mr-3" href="{{ route('notes.index') }}"><i class="material-icons mr-1">fast_rewind</i> Back</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>

        </form>
      </div>
    </div>

@endsection

resources/views/notes/index.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>

        @if ( $query_params = Request::input('q') )

            <li class="breadcrumb-item active"><a href="{{ route('notes.index') }}">{{ $model_title_list['notes'] }}</a></li>
            <li class="breadcrumb-item active">condition(
            @foreach( $query_params as $key => $value )
                @if (!$loop->first) / @endif {{ $key }} : {{ $value }}
            @endforeach
            )</li>
        @else
            <li class="breadcrumb-item active">{{ $model_title_list['notes'] }}</li>
        @endif

      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">view_headline</i>
        <span class="d-inline-block">{{ $model_title_list['notes'] }}</span>
        <a class="btn btn-success d-inline-flex ml-auto" href="{{ route('notes.create') }}"><i class="material-icons align-self-center mr-1">add_circle</i><span class="align-self-center">Create</span></a>
    </h1>

    <p><button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#search-area" aria-expanded="false" aria-controls="search-area">Search</button></p>
    <div class="collapse mb-4" id="search-area">
      <div class="card card-body">

        <form id="search" action="{{ route('notes.index') }}" accept-charset="UTF-8" method="get">
          <input type="hidden" name="q[s]" value="{{ @(Request::input('q')['s']) ?: '' }}" />
          <div class="form-group row">
            <label for="q_id_eq" class="col-sm-2 col-form-label col-form-label-sm">ID</label>
            <div class="col-sm-10">
              <input class="form-control form-control-sm" id="q_id_eq" name="q[id_eq]" type="search" value="{{ @(Request::input('q.id_eq')) }}">
            </div>
          </div>

          <div class="form-group row">
            <label for="q_note_cont" class="col-sm-2 col-form-label col-form-label-sm">Nota</label>
            <div class="col-sm-10">
              <input class="form-control form-control-sm" id="q_note_cont" name="q[note_cont]" type="search" value="{{ @(Request::input('q.note_cont')) }}">
            </div>
          </div>

          <div class="form-group row mb-0">
              <div class="col-sm-10 offset-sm-2">
                  <input type="submit" name="commit" value="Search" class="btn btn-default btn-sm" />
              </div>
          </div>
        </form>

      </div>
    </div>

    @include('notes._table')

@endsection

resources/views/notes/show.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('notes.index') }}">{{ $model_title_list['notes'] }}</a></li>
        <li class="breadcrumb-item active">#{{ $note->id }}</li>
      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">subject</i>
        <span class="d-inline-block">{{ $model_title_list['notes'] }} / Show #{{$note->id}}</span>
        <form class="ml-auto" method="POST" action="{{ route('notes.destroy', $note->id) }}" accept-charset="UTF-8" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
            <div class="btn-group" role="group">
                <a class="btn btn-sm btn-primary" href="{{ route('notes.duplicate', $note->id) }}" data-toggle="tooltip" data-placement="top" title="Duplicate"><i class="material-icons d-block">add_to_photos</i></a>
                <a class="btn btn-sm btn-warning" href="{{ route('notes.edit', $note->id) }}" data-toggle="tooltip" data-placement="top" title="Edit"><i class="material-icons d-block">edit</i></a>
                <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Delete"><i class="material-icons d-block">delete</i></button>
            </div>
        </form>
    </h1> 

    <ul class="list-group list-group-flush mt-4">
      <li class="list-group-item d-inline-flex flex-wrap"><div><strong>ID ： </strong></div><div>{{$note->id}}</div></li>

      <li class="list-group-item d-inline-flex flex-wrap"><div><strong>Nota : </strong></div><div>{{ $note->note }}</div></li>

      <li class="list-group-item d-inline-flex flex-wrap"><div><strong>Planner : </strong></div><div>{{ $note->planner->name or '' }}</div></li>

      <li class="list-group-item"><p><strong>Reminder : </strong></p><div>
        @include('reminders._table', ['reminders' => $note->reminders])
      </div></li>


    </ul>
    <div class="d-flex justify-content-end mt-3">
        <a class="btn btn-secondary d-inline-flex mr-3" href="{{ route('notes.index') }}"><i class="material-icons">fast_rewind</i> Back</a>
    </div>

@endsection