routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
// Route::get("nicePosts/{nicePost}/duplicate", ['as' => 'nicePosts.duplicate', 'uses' => 'NicePostController@duplicate']);
// Route::resource("nicePosts","NicePostController");
// Route::get("beautifulTags/{beautifulTag}/duplicate", ['as' => 'beautifulTags.duplicate', 'uses' => 'BeautifulTagController@duplicate']);
// Route::resource("beautifulTags","BeautifulTagController");
// Route::get("brilliantCategories/{brilliantCategory}/duplicate", ['as' => 'brilliantCategories.duplicate', 'uses' => 'BrilliantCategoryController@duplicate']);
// Route::resource("brilliantCategories","BrilliantCategoryController");
// Route::get("goodComments/{goodComment}/duplicate", ['as' => 'goodComments.duplicate', 'uses' => 'GoodCommentController@duplicate']);
// Route::resource("goodComments","GoodCommentController");

Auth::routes();

Route::get('/', function () { return view('auth.login'); })->middleware('guest');


Route::get('/home', 'HomeController@index')->name('home');

Route::get("users/{user}/duplicate", ['as' => 'users.duplicate', 'uses' => 'UserController@duplicate']);

Route::resource("users","UserController");

Route::get("planners/{planner}/duplicate",
    ['as' => 'planners.duplicate', 'uses' => 'PlannerController@duplicate']);
Route::resource("planners","PlannersController");

Route::get("users/{user}/duplicate",
    ['as' => 'users.duplicate', 'uses' => 'UserController@duplicate']);
Route::resource("users","UserController");
Route::get("planners/{planner}/duplicate",
    ['as' => 'planners.duplicate', 'uses' => 'PlannerController@duplicate']);
Route::resource("planners","PlannerController");
Route::get("notes/{note}/duplicate",
    ['as' => 'notes.duplicate', 'uses' => 'NoteController@duplicate']);
Route::resource("notes","NoteController");
Route::get("tags/{tag}/duplicate",
    ['as' => 'tags.duplicate', 'uses' => 'TagController@duplicate']);
Route::resource("tags","TagController");
Route::get("reminders/{reminder}/duplicate",
    ['as' => 'reminders.duplicate', 'uses' => 'ReminderController@duplicate']);
Route::resource("reminders","ReminderController");

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::resource('planners.notes', 'PlannerNoteController');
// Route::resource('notes.reminders', 'RemainderController');
// Route::get('/planners/{planner}/notes/create', 'NoteController@create');

app/Planner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

// use App\User;
class Planner extends Model
{

    public $rules = [
        'user_id' => 'required',
        'name' => 'required',
    ];
	// Mass Assignment
	protected $fillable = ['name','user_id',];


	// Validate Rule
    public static function getValidateRule(Planner $planner=null){
        if($planner){
            $ignore_unique = $planner->id;
        }else{
            $ignore_unique = 'NULL';
        }
        $table_name = 'planners';
        $validation_rule = [

            'model.name' => 'string',
            'model.user_id' => 'integer',

        ];
        if($planner){

        }
        return $validation_rule;
    }

	public function notes() {
		return $this->hasMany('App\Note');
	}
	public function tags() {
		return $this->hasMany('App\Tag');
	}
	public function user() {
		return $this->belongsTo('App\User');
	}

    public function addNote($note) {
        $this->notes()->create($note);
    }

    public function updateNote($note, $noteId) {
        // \Log::info($note);
        $this->notes()->where('id', '=', $noteId)->update($note);
    }
    //PDO fix
    protected $casts = [
        'user_id' => 'integer'
    ];

	public static function getLists() {
		$lists = [];
		$lists['User'] = User::pluck( 'name' ,'id' );
		$lists['Note'] = Note::pluck( 'note' ,'id' );
		$lists['Tag'] = Tag::pluck( 'tag' ,'id' );
		return $lists;
	}
}

app/Http/Controllers/PlannerController.php
<?php

namespace App\Http\Controllers;

use App\Planner;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\User;
// const USRID = 1;


class PlannerController extends Controller
{





    // public function __construct()
    // {
    //     $this->middleware('auth');
    // }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, User $user)
    {

		$planners = new Planner;

        // (1)filltering
        if( is_array($request->input('q')) ){

            foreach( $request->input('q') as $key => $value ){

                if($key !== 's'){

                    $pettern = '#([^\.]*)\.?([^\.]*)_([^\._]*)#u';
                    preg_match($pettern,$key,$m);

                    $collumn_name = $m[1];
                    $related_column_name = $m[2];

                    if($m[3] == 'eq'){
                        $operator = '=';
                    }elseif($m[3] == 'cont'){
                        $operator = 'like';
                        $value = '%'.$value.'%';
                    }elseif($m[3] == 'gt'){
                        $operator = '>=';
                    }elseif($m[3] == 'lt'){
                        $operator = '<=';
                    }

                    if( $related_column_name !== '' ){  // search at related table column

                        $planners = $planners->whereHas($collumn_name, function($q) use($related_column_name, $operator, $value){
    						$q->where( $related_column_name, $operator, $value );
                        });

                    }else{
                        $planners = $planners->where( $collumn_name, $operator, $value );
                    }
                }
            }
        }
        $planners = auth()->user()->planners()->get();



        // (2)sort
        $q_s = $request->input('q.s');
        if($q_s){

            // sort dir and sort column
            if( substr( $q_s,-5,5 ) === '_desc' ){
                $sort_column = substr( $q_s, 0, strlen($q_s)-5 );
                $planners = $planners->sortByDesc($sort_column);
            }elseif( substr( $q_s,-4,4 ) === '_asc' ){
                $sort_column = substr( $q_s, 0, strlen($q_s)-4 );
                $planners = $planners->sortBy($sort_column);
            }

        }else{
            $planners = $planners->sortByDesc('id');
        }



        // (3)paginate
        $planners = $planners->paginate(10);

		return view('planners.index', compact('planners'));
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('planners.create')->with( 'lists', Planner::getLists() );
    }



    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate_custom($request);

        $input = $request->input('model');
        $input['user_id'] = auth()->user()->id;
        DB::beginTransaction();


		//create data
		$planner = Planner::create( $input );
        // $planner->user_id = auth()->user()->id;
        // dd($planner);
        //sync(attach/detach)
        if($request->input('pivots')){
            $this->sync($request->input('pivots'), $planner);
        }

        DB::commit();

		return redirect()->route('planners.index')->with('message', 'Item created successfully.');
    }



    /**
     * Display the specified resource.
     *
     * @param  \App\Planner  $planner     * @return \Illuminate\Http\Response
     */
    public function show(Planner $planner, User $user)
    {
        // dd(var_dump($this));
        if ($user->can('view', $planner)) {
          return view('planners.show', compact('planner'));
        } else {
          echo 'Not Authorized.';
        }
        // $this->authorize($planner);
        // return $this->makeResponse('planners.show', compact('planner'));
		// return view('planners.show', compact('planner'));
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Planner  $planner     * @return \Illuminate\Http\Response
     */
    public function edit(Planner $planner)
    {
        $this->authorize($planner);
		return view('planners.edit', compact('planner'))->with( 'lists', Planner::getLists() );
    }



	/**
	 * Show the form for duplicatting the specified resource.
	 *
	 * @param \App\Planner  $planner	 * @return \Illuminate\Http\Response
	 */
	public function duplicate(Planner $planner)
	{
        $this->authorize($planner);
		return view('planners.duplicate', compact('planner'))->with( 'lists', Planner::getLists() );
	}



    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Planner  $planner     * @return \Illuminate\Http\Response
     */
    public function update(Planner $planner, Request $request)
    {
        $this->authorize($planner);
        $this->validate_custom($request, $planner);

        $input = $request->input('model');

        DB::beginTransaction();


		//update data
		$planner->update( $input );

        //sync(attach/detach)
        if($request->input('pivots')){
            $this->sync($request->input('pivots'), $planner);
        }

        DB::commit();

		return redirect()->route('planners.index')->with('message', 'Item updated successfully.');
    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Planner  $planner     * @return \Illuminate\Http\Response
     */
    public function destroy(Planner $planner)
    {
        $this->authorize($planner);
		$planner->delete();
		return redirect()->route('planners.index')->with('message', 'Item deleted successfully.');
    }

    /**
     * validate input data.
     *
     * @return array
     */
    public function validate_custom(Request $request, Planner $planner = null)
    {
        $request->validate(Planner::getValidateRule($planner));
    }

    /**
     * sync pivot data
     *
     * @return void
     */
    public function sync($pivots_data, Planner $planner)
    {
        foreach( $pivots_data as $pivot_child_model_name => $pivots ){

            // remove 'id'
            foreach($pivots as &$value){
                if( array_key_exists('id', $value) ){
                    unset($value['id']);
                }
            }unset($value);

            $method = camel_case( str_plural($pivot_child_model_name) );
            $planner->$method()->sync($pivots);
        }
    }
}

resources/views/planners/_form.blade.php
<div class="form-group">
  <label for="name-field">Name Of Planner</label>

  <input type="text" class="form-control
  @if($errors->any()) @if($errors->has("model.name")) is-invalid @else is-valid @endif @endif;
  " id="name-field" name="model[name]" value="@if($errors->any()){{ old('model.name') }}@else{{ $planner->name or '' }}@endif" required>

  @if($errors->has("model.name"))
    <div class="invalid-feedback">{{ $errors->first("model.name") }}</div>
  @else
    <div class="invalid-feedback">Invalid!</div>
  @endif
</div>

resources/views/planners/_table.blade.php
<div class="row">
    <div class="col-md-12">

        @if($planners->count())

            <table class="table table-sm table-striped sp-omit">
              <thead>
                <tr>
                  <th scope="col"><div class="d-flex">
                    @if( method_exists($planners, 'appends') )
                      <a href="javascript:sortByColumn('id')">ID</a>
                      @if( Request::input('q.s') == 'id_asc' )<i class="material-icons">arrow_drop_up</i>
                      @elseif( Request::input('q.s') == 'id_desc' )<i class="material-icons">arrow_drop_down</i> @endif
                    @else
                      ID
                    @endif
                  </div></th>
                  <th scope="col"><div class="d-flex">
                    @if( method_exists($planners, 'appends') )
                      <a href="javascript:sortByColumn('name')">Name Of Planner</a>
                      @if( Request::input('q.s') == 'name_asc' )<i class="material-icons">arrow_drop_up</i>
                      @elseif( Request::input('q.s') == 'name_desc' )<i class="material-icons">arrow_drop_down</i> @endif
                    @else
                      Name Of Planner                    @endif
                  </div></th>

                  <th scope="col">USER</th>

                  <th scope="col">Note</th>
                  <th scope="col">Tag</th>


                  <th class="text-right" scope="col">OPTIONS</th>
                </tr>
              </thead>
              <tbody>
                @foreach($planners as $planner)
                    <tr>
                      <td scope="row"><a href="{{ route('planners.show', $planner->id) }}">{{$planner->id}}</a></td>
                      <td><a href="{{ route('planners.notes.index', $planner->id) }}" >{{$planner->name}}</a></td>

                      <td>@if($planner->user)<a href="{{ route('users.show', $planner->user->id) }}">{{ $planner->user->name }}</a>@else - @endif</td>

                      <td>
                          @foreach($planner->notes as $note)
                                        @if (!$loop->first) , @endif
                                        <a href="{{ route('planners.notes.show', [$planner->id, $note->id]) }}">{{ $note->note }}</a>
                          @endforeach
                      </td>
                      <td>
                          @foreach($planner->tags as $tag)
                                        @if (!$loop->first) , @endif
                                        <a href="{{ route('tags.show', $tag->id) }}">{{ $tag->tag }}</a>
                          @endforeach
                      </td>


                      <td class="text-right">
                        <div class="btn-group" role="group">
                            <a class="btn btn-sm btn-primary" href="{{ route('planners.notes.create', $planner->id) }}" data-toggle="tooltip" data-placement="top" title="Add Note to Planner"><i class="material-icons d-block">note_add</i></a>
                            <a class="btn btn-sm btn-warning" href="{{ route('planners.edit', $planner->id) }}" data-toggle="tooltip" data-placement="top" title="Edit Planner"><i class="material-icons d-block">edit</i></a>
                            <form method="POST" action="{{ route('planners.destroy', $planner->id) }}" accept-charset="UTF-8" style="display: inline;" onsubmit="if(confirm('Delete Planner? Are you sure?')) { return true } else {return false };">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Delete Planner"><i class="material-icons d-block">delete</i></button>
                            </form>
                        </div>
                      </td>
                    </tr>
                @endforeach
              </tbody>
            </table>
            @if( method_exists($planners, 'appends') )
              {!! $planners->appends(Request::except('page'))->render() !!}
            @endif
        @else
            <h3 class="text-center alert alert-info">Empty!</h3>
        @endif
    </div>
</div>

resources/views/planners/create.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('planners.index') }}">{{ $model_title_list['planners'] }}</a></li>
        <li class="breadcrumb-item active">Create</li>
      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">add_circle</i>
        <span class="d-inline-block">{{ $model_title_list['planners'] }} / Create</span>
    </h1> 

    <div class="row">
      <div class="col-md-12">
        <form method="POST" action="{{ route('planners.store') }}" accept-charset="UTF-8" class="needs-validation" novalidate>
          {{ csrf_field() }}

@include('planners._form', ['mode' => 'create'])

          <div class="d-flex justify-content-end">
            <a class="btn btn-secondary d-inline-flex mr-3" href="{{ route('planners.index') }}"><i class="material-icons mr-1">fast_rewind</i> Back</a>
            <button type="submit" class="btn btn-primary">Create</button>
          </div>

        </form>
      </div>
    </div>

@endsection

resources/views/planners/duplicate.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('planners.index') }}">{{ $model_title_list['planners'] }}</a></li>
        <li class="breadcrumb-item active">Duplicate</li>
      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">add_to_photos</i>
        <span class="d-inline-block">{{ $model_title_list['planners'] }} / Duplicate #{{$planner->id}}</span>
    </h1> 

    <div class="row">
      <div class="col-md-12">
        <form method="POST" action="{{ route('planners.store') }}" accept-charset="UTF-8" class="needs-validation" novalidate>
          {{ csrf_field() }}

@include('planners._form', ['mode' => 'duplicate'])

          <div class="d-flex justify-content-end">
            <a class="btn btn-secondary d-inline-flex mr-3" href="{{ route('planners.index') }}"><i class="material-icons mr-1">fast_rewind</i> Back</a>
            <button type="submit" class="btn btn-primary">Duplicate</button>
          </div>

        </form>
      </div>
    </div>

@endsection

resources/views/planners/edit.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('planners.index') }}">{{ $model_title_list['planners'] }}</a></li>
        <li class="breadcrumb-item"><a href="{{ route('planners.show', $planner->id) }}">{{ $planner->id }}</a></li>
        <li class="breadcrumb-item active">Edit</li>
      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">edit</i>
        <span class="d-inline-block">{{ $model_title_list['planners'] }} / Edit #{{$planner->id}}</span>
    </h1> 

    <div class="row">
      <div class="col-md-12">
        <form method="POST" action="{{ route('planners.update', $planner->id) }}" accept-charset="UTF-8" class="needs-validation" novalidate>
          {{ method_field('PUT') }}
          {{ csrf_field() }}

@include('planners._form', ['mode' => 'edit'])

          <div class="d-flex justify-content-end">
            <a class="btn btn-secondary d-inline-flex mr-3" href="{{ route('planners.index') }}"><i class="material-icons mr-1">fast_rewind</i> Back</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>

        </form>
      </div>
    </div>

@endsection

resources/views/planners/index.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>

        @if ( $query_params = Request::input('q') )
        
            <li class="breadcrumb-item active"><a href="{{ route('planners.index') }}">{{ $model_title_list['planners'] }}</a></li>
            <li class="breadcrumb-item active">condition(  
            @foreach( $query_params as $key => $value )
                @if (!$loop->first) / @endif {{ $key }} : {{ $value }}
            @endforeach
            )</li>
        @else
            <li class="breadcrumb-item active">{{ $model_title_list['planners'] }}</li>
        @endif

      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">view_headline</i>
        <span class="d-inline-block">{{ $model_title_list['planners'] }}</span>
        <a class="btn btn-success d-inline-flex ml-auto" href="{{ route('planners.create') }}"><i class="material-icons align-self-center mr-1">add_circle</i><span class="align-self-center">Create</span></a>
    </h1> 

    <p><button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#search-area" aria-expanded="false" aria-controls="search-area">Search</button></p>
    <div class="collapse mb-4" id="search-area">
      <div class="card card-body">

        <form id="search" action="{{ route('planners.index') }}" accept-charset="UTF-8" method="get">
          <input type="hidden" name="q[s]" value="{{ @(Request::input('q')['s']) ?: '' }}" />
          <div class="form-group row">
            <label for="q_id_eq" class="col-sm-2 col-form-label col-form-label-sm">ID</label>
            <div class="col-sm-10">
              <input class="form-control form-control-sm" id="q_id_eq" name="q[id_eq]" type="search" value="{{ @(Request::input('q.id_eq')) }}">
            </div>
          </div>

          <div class="form-group row">
            <label for="q_name_cont" class="col-sm-2 col-form-label col-form-label-sm">Name Of Planner</label>
            <div class="col-sm-10">
              <input class="form-control form-control-sm" id="q_name_cont" name="q[name_cont]" type="search" value="{{ @(Request::input('q.name_cont')) }}">
            </div>
          </div>

          <div class="form-group row mb-0">
              <div class="col-sm-10 offset-sm-2">
                  <input type="submit" name="commit" value="Search" class="btn btn-default btn-sm" />
              </div>
          </div>
        </form>

      </div>
    </div>

    @include('planners._table')

@endsection

resources/views/planners/show.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('planners.index') }}">{{ $model_title_list['planners'] }}</a></li>
        <li class="breadcrumb-item active">#{{ $planner->id }}</li>
      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">subject</i>
        <span class="d-inline-block">{{ $model_title_list['planners'] }} / Show #{{$planner->id}}</span>
        <form class="ml-auto" method="POST" action="{{ route('planners.destroy', $planner->id) }}" accept-charset="UTF-8" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
            <div class="btn-group" role="group">
{{--                 <a class="btn btn-sm btn-primary" href="{{ route('planners.duplicate', $planner->id) }}" data-toggle="tooltip" data-placement="top" title="Duplicate"><i class="material-icons d-block">add_to_photos</i></a> --}}
                <a class="btn btn-sm btn-warning" href="{{ route('planners.edit', $planner->id) }}" data-toggle="tooltip" data-placement="top" title="Edit"><i class="material-icons d-block">edit</i></a>
                <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Delete"><i class="material-icons d-block">delete</i></button>
            </div>
        </form>
    </h1>

    <ul class="list-group list-group-flush mt-4">
      <li class="list-group-item d-inline-flex flex-wrap"><div><strong>ID ： </strong></div><div>{{$planner->id}}</div></li>

      <li class="list-group-item d-inline-flex flex-wrap"><div><strong>Name Of Planner : </strong></div><div>{{ $planner->name }}</div></li>

      <li class="list-group-item d-inline-flex flex-wrap"><div><strong>USER : </strong></div><div>{{ $planner->user->name or '' }}</div></li>

      <li class="list-group-item"><p><strong>Note : </strong></p><div>
        @include('plannerNotes._table', ['notes' => $planner->notes])
      </div></li>
      <li class="list-group-item"><p><strong>Tag : </strong></p><div>
        @include('tags._table', ['tags' => $planner->tags])
      </div></li>


    </ul>
    <div class="d-flex justify-content-end mt-3">
        <a class="btn btn-secondary d-inline-flex mr-3" href="{{ route('planners.index') }}"><i class="material-icons">fast_rewind</i> Back</a>
    </div>

@endsection