routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
// Route::get("nicePosts/{nicePost}/duplicate", ['as' => 'nicePosts.duplicate', 'uses' => 'NicePostController@duplicate']);
// Route::resource("nicePosts","NicePostController");
// Route::get("beautifulTags/{beautifulTag}/duplicate", ['as' => 'beautifulTags.duplicate', 'uses' => 'BeautifulTagController@duplicate']);
// Route::resource("beautifulTags","BeautifulTagController");
// Route::get("brilliantCategories/{brilliantCategory}/duplicate", ['as' => 'brilliantCategories.duplicate', 'uses' => 'BrilliantCategoryController@duplicate']);
// Route::resource("brilliantCategories","BrilliantCategoryController");
// Route::get("goodComments/{goodComment}/duplicate", ['as' => 'goodComments.duplicate', 'uses' => 'GoodCommentController@duplicate']);
// Route::resource("goodComments","GoodCommentController");

Auth::routes();

Route::get('/', function () { return view('auth.login'); })->middleware('guest');


Route::get('/home', 'HomeController@index')->name('home');

Route::get("users/{user}/duplicate", ['as' => 'users.duplicate', 'uses' => 'UserController@duplicate']);

Route::resource("users","UserController");

Route::get("planners/{planner}/duplicate",
    ['as' => 'planners.duplicate', 'uses' => 'PlannerController@duplicate']);
Route::resource("planners","PlannersController");

Route::get("users/{user}/duplicate",
    ['as' => 'users.duplicate', 'uses' => 'UserController@duplicate']);
Route::resource("users","UserController");
Route::get("planners/{planner}/duplicate",
    ['as' => 'planners.duplicate', 'uses' => 'PlannerController@duplicate']);
Route::resource("planners","PlannerController");
Route::get("notes/{note}/duplicate",
    ['as' => 'notes.duplicate', 'uses' => 'NoteController@duplicate']);
Route::resource("notes","NoteController");
Route::get("tags/{tag}/duplicate",
    ['as' => 'tags.duplicate', 'uses' => 'TagController@duplicate']);
Route::resource("tags","TagController");
Route::get("reminders/{reminder}/duplicate",
    ['as' => 'reminders.duplicate', 'uses' => 'ReminderController@duplicate']);
Route::resource("reminders","ReminderController");

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::resource('planners.notes', 'PlannerNoteController');
// Route::resource('notes.reminders', 'RemainderController');
// Route::get('/planners/{planner}/notes/create', 'NoteController@create');

app/Http/Controllers/PlannerNoteController.php
<?php

namespace App\Http\Controllers;

use App\Note;
use App\Planner;
use App\PlannerNote;
// use Illuminate\Http\Request;
use App\Notifications\UserCommented;

class PlannerNoteController extends Controller
{

    public function index(Planner $planner)
    {
        // $plannerNotes = $planner->notes;
        return view('plannerNotes.index', compact('planner'));
    }

    public function show(Planner $planner, Note $note)
    {
        // $planner = Planner::with('notes')->findOrFail($plannerId);
        // $note = $planner->notes()->findOrFail($noteId);
        $plannerId = $planner->id;
        return view('plannerNotes.show', compact('note','plannerId'));

    }

    public function edit($plannerId, $noteId)
    {
        $planner = Planner::with('notes')->findOrFail($plannerId);
        $note = $planner->notes()->findOrFail($noteId);
        return view('plannerNotes.edit', compact('note','plannerId'))->with( 'lists', Note::getLists() );
    }

    public function update(Planner $planner, $noteId)
    {
        // TODO: add validation
        $planner->updateNote(request('body'), $noteId);
        return redirect()->route('planners.notes.index', $planner->id)->with('message', 'Item updated successfully.');
    }

    public function create($plannerId)
    {
        return view('plannerNotes.create', compact('plannerId'))->with( 'lists', Note::getLists() );
    }

    public function store(Planner $planner)
    {
        // TODO: add validation
        $planner->addNote(request('body'));
        return redirect()->route('planners.notes.index', $planner->id)->with('message', 'Item created successfully.');
    }

    public function destroy($plannerId, Note $note)
    {
        $note->delete();
        return redirect()->route('planners.notes.index', $plannerId)->with('message', 'Item deleted successfully.');
    }







    // public function index(Request $request)
    // {
    //     $photo = Planner::with('notes')->findOrFail($request->route('planner'));

    //     return response()->json(['data' => $photo->notes]);
    // }

    // public function store(Request $request, Planner $photo)
    // {
    //     $data = $request->validate(['note' => 'required|string|between:2,500']);

    //     $comment = PlannerNote::create([
    //         'photo_id' => $photo->id,
    //         'comment' => $data['comment'],
    //         'user_id' => $request->user()->id,
    //     ]);

    //     if ($photo->user->allowsCommentsNotifications($request->user())) {
    //         $comment->notify(new UserCommented($request->user(), $photo, $comment));
    //     }

    //     return response()->json([
    //         'status' => 'success',
    //         'data' => $comment->load('user')
    //     ]);
    // }
}

resources/views/plannerNotes/_form.blade.php
<div class="form-group">
  <label for="note-field">Nota</label>

  <textarea class="form-control
  @if($errors->any()) @if($errors->has("body.note")) is-invalid @else is-valid @endif @endif;
  " id="note-field" name="body[note]" rows="3" required>@if($errors->any()){{ old('body.note') }}@else{{ $note->note or '' }}@endif</textarea>

  @if($errors->has("body.note"))
    <div class="invalid-feedback">{{ $errors->first("body.note") }}</div>
  @else
    <div class="invalid-feedback">Invalid!</div>
  @endif
</div>




{{-- <p>Uhu: {{ var_dump($lists) }}</p> --}}

{{-- <div class="form-group">
  <label for="planner_id-field">Planner</label>
  <select class="form-control
  @if($errors->any()) @if($errors->has("model.planner_id")) is-invalid @else is-valid @endif @endif
  " id="planner_id-field" name="model[planner_id]">
    <option value=""></option>
  @foreach( $lists["Planner"] as $list_key => $list_item )
    <option value="{{ $list_key }}"
      @if($errors->any())
        @if( old('planner_id') == $list_key ) selected='selected' @endif
      @else
        @if( isset($note) && $note->planner_id==$list_key )  selected='selected' @endif
      @endif
   >{{ $list_item }}</option>
  @endforeach
  </select>
  @if($errors->has("model.planner_id"))
    <div class="invalid-feedback">{{ $errors->first("model.planner_id") }}</div>
  @else
    <div class="invalid-feedback">Invalid!</div>
  @endif
</div> --}}

resources/views/plannerNotes/_table.blade.php
<div class="row">
    <div class="col-md-12">

        @if($planner->notes->count())

            <table class="table table-sm table-striped sp-omit">
              <thead>
                <tr>
                  <th scope="col"><div class="d-flex">
                    @if( method_exists($planner->notes, 'appends') )
                      <a href="javascript:sortByColumn('id')">ID</a>
                      @if( Request::input('q.s') == 'id_asc' )<i class="material-icons">arrow_drop_up</i>
                      @elseif( Request::input('q.s') == 'id_desc' )<i class="material-icons">arrow_drop_down</i> @endif
                    @else
                      ID
                    @endif
                  </div></th>
                  <th scope="col"><div class="d-flex">
                    @if( method_exists($planner->notes, 'appends') )
                      <a href="javascript:sortByColumn('note')">Nota</a>
                      @if( Request::input('q.s') == 'note_asc' )<i class="material-icons">arrow_drop_up</i>
                      @elseif( Request::input('q.s') == 'note_desc' )<i class="material-icons">arrow_drop_down</i> @endif
                    @else
                      Nota                    @endif
                  </div></th>

                  <th scope="col">Planner</th>

                  <th scope="col">Reminder</th>


                  <th class="text-right" scope="col">OPTIONS</th>
                </tr>
              </thead>
              <tbody>
                @foreach($planner->notes as $note)
                    <tr>
                      <td scope="row"><a href="{{ route('planners.notes.show', [$note->planner->id, $note->id]) }}">{{$note->id}}</a></td>
                      <td>{{$note->note}}</td>

                      <td>@if($note->planner)<a href="{{ route('planners.show', $note->planner->id) }}">{{ $note->planner->name }}</a>@else - @endif</td>

                      <td>
                          @foreach($note->reminders as $reminder)
                                        @if (!$loop->first) , @endif
                                        <a href="{{ route('reminders.show', $reminder->id) }}">{{ $reminder->when }}</a>
                          @endforeach
                      </td>


                      <td class="text-right">
                        <div class="btn-group" role="group">
                            {{-- <a class="btn btn-sm btn-primary" href="{{ route('notes.duplicate', $note->id) }}" data-toggle="tooltip" data-placement="top" title="Duplicate"><i class="material-icons d-block">add_to_photos</i></a> --}}
                            <a class="btn btn-sm btn-warning" href="{{ route('planners.notes.edit', [$planner->id, $note->id]) }}" data-toggle="tooltip" data-placement="top" title="Edit"><i class="material-icons d-block">edit</i></a>
                            <form method="POST" action="{{ route('planners.notes.destroy', [$planner->id, $note->id]) }}" accept-charset="UTF-8" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Delete"><i class="material-icons d-block">delete</i></button>
                            </form>
                        </div>
                      </td>
                    </tr>
                @endforeach
              </tbody>
            </table>
            @if( method_exists($planner->notes, 'appends') )
              {!! $planner->notes->appends(Request::except('page'))->render() !!}
            @endif
        @else
            <h3 class="text-center alert alert-info">Empty!</h3>
        @endif
    </div>
</div>

resources/views/plannerNotes/_tableReminders.blade.php
<div class="row">
    <div class="col-md-12">

        @if($reminders->count())

            <table class="table table-sm table-striped sp-omit">
              <thead>
                <tr>
                  <th scope="col"><div class="d-flex">
                    @if( method_exists($reminders, 'appends') )
                      <a href="javascript:sortByColumn('id')">ID</a>
                      @if( Request::input('q.s') == 'id_asc' )<i class="material-icons">arrow_drop_up</i>
                      @elseif( Request::input('q.s') == 'id_desc' )<i class="material-icons">arrow_drop_down</i> @endif
                    @else
                      ID
                    @endif
                  </div></th>
                  <th scope="col"><div class="d-flex">
                    @if( method_exists($reminders, 'appends') )
                      <a href="javascript:sortByColumn('when')">When?</a>
                      @if( Request::input('q.s') == 'when_asc' )<i class="material-icons">arrow_drop_up</i>
                      @elseif( Request::input('q.s') == 'when_desc' )<i class="material-icons">arrow_drop_down</i> @endif
                    @else
                      When?                    @endif
                  </div></th>

{{--                   <th scope="col">Note</th> --}}



                  <th class="text-right" scope="col">OPTIONS</th>
                </tr>
              </thead>
              <tbody>
                @foreach($reminders as $reminder)
                    <tr>
                      <td scope="row"><a href="{{ route('reminders.show', $reminder->id) }}">{{$reminder->id}}</a></td>
                      <td>{{$reminder->when}} UTC</td>
{{--
                      <td>@if($reminder->note)<a href="{{ route('planners.notes.show', [$reminder->note->planner->id, $reminder->note->id]) }}">{{ $reminder->note->note }}</a>@else - @endif</td> --}}



                      <td class="text-right">
                        <div class="btn-group" role="group">
                            <a class="btn btn-sm btn-primary" href="{{ route('reminders.duplicate', $reminder->id) }}" data-toggle="tooltip" data-placement="top" title="Duplicate"><i class="material-icons d-block">add_to_photos</i></a>
                            <a class="btn btn-sm btn-warning" href="{{ route('reminders.edit', $reminder->id) }}" data-toggle="tooltip" data-placement="top" title="Edit"><i class="material-icons d-block">edit</i></a>
                            <form method="POST" action="{{ route('reminders.destroy', $reminder->id) }}" accept-charset="UTF-8" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Delete"><i class="material-icons d-block">delete</i></button>
                            </form>
                        </div>
                      </td>
                    </tr>
                @endforeach
              </tbody>
            </table>
            @if( method_exists($reminders, 'appends') )
              {!! $reminders->appends(Request::except('page'))->render() !!}
            @endif
        @else
            <h3 class="text-center alert alert-info">Empty!</h3>
        @endif
    </div>
</div>

resources/views/plannerNotes/create.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('notes.index') }}">{{ $model_title_list['notes'] }}</a></li>
        <li class="breadcrumb-item active">Create</li>
      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">add_circle</i>
        <span class="d-inline-block">{{ $model_title_list['notes'] }} / Create</span>
    </h1>

    <div class="row">
      <div class="col-md-12">
        <form method="POST" action="{{ route('planners.notes.store', $plannerId) }}" accept-charset="UTF-8" class="needs-validation" novalidate>
          {{ csrf_field() }}

@include('plannerNotes._form', ['mode' => 'create'])

          <div class="d-flex justify-content-end">
            <a class="btn btn-secondary d-inline-flex mr-3" href="{{ route('planners.notes.index', $plannerId) }}"><i class="material-icons mr-1">fast_rewind</i> Back</a>
            <button type="submit" class="btn btn-primary">Create</button>
          </div>

        </form>
      </div>
    </div>

@endsection

resources/views/plannerNotes/edit.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('notes.index') }}">{{ $model_title_list['notes'] }}</a></li>
        <li class="breadcrumb-item"><a href="{{ route('notes.show', $note->id) }}">{{ $note->id }}</a></li>
        <li class="breadcrumb-item active">Edit</li>
      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">edit</i>
        <span class="d-inline-block">{{ $model_title_list['notes'] }} / Edit #{{$note->id}}</span>
    </h1>

    <div class="row">
      <div class="col-md-12">
        <form method="POST" action="{{ route('planners.notes.update', [$plannerId, $note->id]) }}" accept-charset="UTF-8" class="needs-validation" novalidate>
          {{ method_field('PUT') }}
          {{ csrf_field() }}

@include('plannerNotes._form', ['mode' => 'edit'])

          <div class="d-flex justify-content-end">
            <a class="btn btn-secondary d-inline-flex mr-3" href="{{ route('planners.notes.index', $plannerId) }}"><i class="material-icons mr-1">fast_rewind</i> Back</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>

        </form>
      </div>
    </div>

@endsection

resources/views/plannerNotes/index.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>

        @if ( $query_params = Request::input('q') )

            <li class="breadcrumb-item active"><a href="{{ route('planners.notes.index', $planner->id) }}">{{ $model_title_list['notes'] }}</a></li>
            <li class="breadcrumb-item active">condition(
            @foreach( $query_params as $key => $value )
                @if (!$loop->first) / @endif {{ $key }} : {{ $value }}
            @endforeach
            )</li>
        @else
            <li class="breadcrumb-item active">{{ $model_title_list['notes'] }}</li>
        @endif

      </ol>
    </nav>
@endsection

@section('content')

    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">view_headline</i>
        <span class="d-inline-block">{{ $model_title_list['notes'] }}</span>
        <a class="btn btn-success d-inline-flex ml-auto" href="{{ route('planners.notes.create', $planner->id) }}"><i class="material-icons align-self-center mr-1">add_circle</i><span class="align-self-center">Create</span></a>
    </h1>

    <p><button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#search-area" aria-expanded="false" aria-controls="search-area">Search</button></p>
    <div class="collapse mb-4" id="search-area">
      <div class="card card-body">

        <form id="search" action="{{ route('notes.index') }}" accept-charset="UTF-8" method="get">
          <input type="hidden" name="q[s]" value="{{ @(Request::input('q')['s']) ?: '' }}" />
          <div class="form-group row">
            <label for="q_id_eq" class="col-sm-2 col-form-label col-form-label-sm">ID</label>
            <div class="col-sm-10">
              <input class="form-control form-control-sm" id="q_id_eq" name="q[id_eq]" type="search" value="{{ @(Request::input('q.id_eq')) }}">
            </div>
          </div>

          <div class="form-group row">
            <label for="q_note_cont" class="col-sm-2 col-form-label col-form-label-sm">Nota</label>
            <div class="col-sm-10">
              <input class="form-control form-control-sm" id="q_note_cont" name="q[note_cont]" type="search" value="{{ @(Request::input('q.note_cont')) }}">
            </div>
          </div>

          <div class="form-group row mb-0">
              <div class="col-sm-10 offset-sm-2">
                  <input type="submit" name="commit" value="Search" class="btn btn-default btn-sm" />
              </div>
          </div>
        </form>

      </div>
    </div>

    @include('plannerNotes._table')

@endsection

resources/views/plannerNotes/show.blade.php
@extends('layout')

@section('breadcrumb')
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/" class="d-inline-flex"><i class="material-icons mr-1">home</i> Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('planners.notes.index', $plannerId) }}">{{ $model_title_list['notes'] }}</a></li>
        <li class="breadcrumb-item active">#{{ $note->id }}</li>
      </ol>
    </nav>
@endsection


@section('content')

@section('content')
    <h3>Planner id: {{ $plannerId }}</h3>
    <h1 class="d-flex mb-3">
        <i class="material-icons align-self-center mr-1">subject</i>
        <span class="d-inline-block">{{ $model_title_list['notes'] }} / Show #{{$note->id}}</span>
        <form class="ml-auto" method="POST" action="{{ route('notes.destroy', $note->id) }}" accept-charset="UTF-8" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
            <div class="btn-group" role="group">
{{--                 <a class="btn btn-sm btn-primary" href="{{ route('planners.notes.duplicate', [$plannerId, $note->id]) }}" data-toggle="tooltip" data-placement="top" title="Duplicate"><i class="material-icons d-block">add_to_photos</i></a> --}}
                <a class="btn btn-sm btn-warning" href="{{ route('planners.notes.edit', [$plannerId, $note->id]) }}" data-toggle="tooltip" data-placement="top" title="Edit"><i class="material-icons d-block">edit</i></a>
                <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top" title="Delete"><i class="material-icons d-block">delete</i></button>
            </div>
        </form>
    </h1>

    <ul class="list-group list-group-flush mt-4">
      <li class="list-group-item d-inline-flex flex-wrap"><div><strong>ID ： </strong></div><div>{{$note->id}}</div></li>

      <li class="list-group-item d-inline-flex flex-wrap"><div><strong>Nota : </strong></div><div>{{ $note->note }}</div></li>

      <li class="list-group-item d-inline-flex flex-wrap"><div><strong>Planner : </strong></div><div>{{ $note->planner->name or '' }}</div></li>

      <li class="list-group-item"><p><strong>Reminder : </strong></p><div>
        @include('plannerNotes._tableReminders', ['reminders' => $note->reminders])
      </div></li>
      <li class="list-group-item"><p><strong>Reminder Add: </strong></p><div>
        <form method="POST" action="/reminders" class="needs-validation form-inline custom-form">
            @csrf
            <input type="hidden" name="model[note_id]" value="{{$note->id}}">
            <div class="form-group">
              <label for="when-field">When?</label>
              <input class="form-control" type="datetime-local" class="form-control" id='when-field' name="model[when]" value="" required>
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </form>
      </div></li>


    </ul>
    <div class="d-flex justify-content-end mt-3">
        <a class="btn btn-secondary d-inline-flex mr-3" href="{{ route('planners.notes.index', $plannerId) }}"><i class="material-icons">fast_rewind</i> Back</a>
    </div>

@endsection

@endsection